version: "3.8"

services:

  db:
    image: mysql:latest
    container_name: my-mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=P@$$w0rd123
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=P@$$w0rd
  
volumes:
  db: 
    driver: local
