version: "3.8"

services:

  db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_PASSWORD: root123
    ports:
      - "5433:5432"
    volumes: 
      - db:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  cache:
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
  
volumes:
  db: 
    driver: local
  cache: 
    driver: local
