// <auto-generated />
using System;
using AviationApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AviationApp.Infrastructure.Migrations
{
    [DbContext(typeof(AviationDbContext))]
    partial class AviationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AviationApp.Domain.Entities.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirportId")
                        .HasColumnType("int")
                        .HasColumnName("airport_id");

                    b.Property<string>("AirportName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("airport_name");

                    b.Property<string>("CountryName")
                        .HasColumnType("longtext")
                        .HasColumnName("country_name");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("timezone");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("airport", (string)null);
                });

            modelBuilder.Entity("AviationApp.Domain.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AirlineName")
                        .HasColumnType("longtext")
                        .HasColumnName("airline_name");

                    b.Property<string>("ArrivalAirport")
                        .HasColumnType("longtext")
                        .HasColumnName("arrival_airport");

                    b.Property<DateTime>("ArrivalScheduled")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("arrival_scheduled");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("departure_airport");

                    b.Property<DateTime>("DepartureScheduled")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("departure_scheduled");

                    b.Property<DateTime>("FlightDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("flight_date");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("flight_number");

                    b.Property<string>("FlightStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("flight_status");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("flight", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
